// users
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const REGISTER_USER_INIT = 'REGISTER_USER_INIT'

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_INIT = 'LOGIN_USER_INIT';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST';
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';

// categories
export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'

export const ADD_CATEGORY_REQUEST = 'ADD_CATEGORY_REQUEST'
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE'

export const EDIT_CATEGORY_REQUEST = 'EDIT_CATEGORY_REQUEST'
export const EDIT_CATEGORY_FAILURE = 'EDIT_CATEGORY_FAILURE'

export const GET_ONE_CATEGORY_REQUEST = 'GET_ONE_CATEGORY_REQUEST'
export const GET_ONE_CATEGORY_SUCCESS = 'GET_ONE_CATEGORY_SUCCESS'

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST'

// articles
export const ADD_ARTICLE_REQUEST = 'ADD_ARTICLE_REQUEST'
export const ADD_ARTICLE_FAILURE = 'ADD_ARTICLE_FAILURE'

export const REMOVE_ARTICLE_REQUEST = 'REMOVE_ARTICLE_REQUEST'
export const REMOVE_ARTICLE_FAILURE = 'REMOVE_ARTICLE_FAILURE'

export const EDIT_ARTICLE_REQUEST = 'EDIT_ARTICLE_REQUEST'
export const EDIT_ARTICLE_FAILURE = 'EDIT_ARTICLE_FAILURE'

export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST'
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS'

export const GET_ALL_CATEGORIES_REQUEST = 'GET_ALL_ARTICLES_REQUEST'

export const GET_ARTICLE_REQUEST = 'GET_ARTICLE_REQUEST'
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS'

export const ARTICLE_INIT = 'ARTICLE_INIT'